updated readme to include that OPR is in beta as pointed out by the i…
CaravanStudios/open-product-recovery pull request #78
Opened 2022-12-31 01:31 UTC by TerryTong-Git

…ssues tab

Fixes #<45>

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

2023-01-05 16:22 UTC, johndayrichter commented on components/core/src/server/installable-endpoints/ingest.ts
> +export const ingestEndpoint = (api: IntegrationApi, s: OprServer): any => {
Please change the return type of this function to "unknown" (or, even better, the upcoming opr-core/JsonValue interface). Our lint rules disallow "any" types except when absolutely necessary.

Thanks!

2023-01-11 18:30 UTC, johndayrichter requested changes
Sorry this took me so long to review - we've been swamped with issue #79.

Thanks for fixing the README and adding those utility endpoints. As you'll see from the per-file comments, I think the README change ought to be broken out from the other change. PR #79 makes major changes to the way integrations are installed, which will force some other changes to the endpoints you've added. But I've still commented on those files, just to lay out some issues about package setup and everything.

Thanks so much for contributing, and I hope you'll consider breaking up this PR so we can take your README changes ASAP!

2023-01-11 18:30 UTC, johndayrichter commented on README.md
> +
Thanks for this! I think this change ought to be broken out into a different PR. We could merge that immediately.

2023-03-10 20:47 UTC, rvenables commented on README.md
> +The Current Version of OPR is in beta and the major version is 0. All changes to the library may by breaking changes. Please refer to the discussions for details on updates. (https://github.com/googl
Note the updated github URL (https://github.com/CaravanStudios/open-product-recovery). @TerryTong-Git: Still interested in making this change?

2023-04-14 19:52 UTC, rvenables commented on README.md
> +The Current Version of OPR is in beta and the major version is 0. All changes to the library may by breaking changes. Please refer to the discussions for details on updates. (https://github.com/googl
@TerryTong-Git thank you for your contribution. We're going to assume this is abandoned for now and make this change.

2024-03-08 20:56 UTC, rvenables commented
Closing as abandoned

2024-03-08 20:56 UTC, closed without merging